name: iris-prediction
channels:
  - defaults
dependencies:
  - numpy==1.21.4
  - pandas==1.2.5
  - scikit-learn==0.24.2
  - matplotlib
  - boto3
  - pip
  - pip:
    - mlflow==1.21.0
    - xgboost==1.5.1
    
